Added missing header file for 'exit' command
Got this error
```
mih/src/linscan.cpp:63:7: error: use of undeclared identifier 'exit'
                    exit(1);
```
from clang after calling `make`.